<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>PolarisRes</AssemblyName>
    <RootNamespace>Polaris.Res</RootNamespace>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PolarisCore\PolarisCore.csproj" />
    <PackageReference Include="NVorbis" Version="0.10.*" />
  </ItemGroup>
  <Import Project="build\Polaris.Runtime.props" />
</Project>
